wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/text2reward/run_metaworld/sac.py
    python_version: 3.10.13
    cli_version: 0.21.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1760649354
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 4
      - 13
      - 16
      - 22
      - 35
      - 42
      4: 3.10.13
      5: 0.21.2
      13: linux-x86_64
    e:
      0lqg3d3lab79fo5aanhd97g52xzxpsz7:
        os: Linux-4.18.0-553.77.1.el8_10.x86_64-x86_64-Intel-R-_Xeon-R-_Gold_6148_CPU_@_2.40GHz-with-glibc2.37
        python: CPython 3.10.13
        started_at: '2025-10-16T21:15:48.056887Z'
        args:
        - --env_id
        - button-press-v3
        - --train_num
        - '8'
        - --eval_num
        - '5'
        - --eval_freq
        - '16_000'
        - --max_episode_steps
        - '500'
        - --train_max_steps
        - '1_000_000'
        - --seed
        - '12345'
        - --exp_name
        - zero-shot
        - --reward_path
        - ./reward_code/button-press-v3/specific.py
        program: /lustre04/scratch/yingyue/LLMR/text2reward/./run_metaworld/sac.py
        code_path: text2reward/run_metaworld/sac.py
        code_path_local: run_metaworld/sac.py
        git:
          remote_url: https://github.com/yingyue3/LLMR.git
          commit: a1d657b3feb710116d705f472be1b98abe722529
        root: /lustre04/scratch/yingyue/LLMR/text2reward
        host: beluga4.int.ets1.calculquebec.ca
        executable: /lustre04/scratch/yingyue/rwvenv/bin/python
        cpu_count: 40
        cpu_count_logical: 40
        disk:
          /:
            total: '17179869184'
            used: '6277181440'
        memory:
          total: '201363034112'
        slurm:
          mpi_type: pmix
        writer_id: 0lqg3d3lab79fo5aanhd97g52xzxpsz7
env:
  desc: null
  value: button-press-v3
